<img src= "https://maua.br/images/logo-IMT.png" width=250>

#  <center> <font color=#023e8a>  **ID201: Geometria Analítica para Inteligência Artificial e Ciência de Dados.**  <center>
 <center> Prof. Sandro Martini <center>

## <center>  **Semana 08: Distância Euclidiana**

### Nome: não esqueçam de colocar o seu  nome aqui

*   Alexandre Raminelli | 24.01625-0



***

### **Atividade 1**

Classificar uma nova imagem com base em sua similaridade com duas imagens conhecidas, utilizando vetores e o cálculo da distância euclidiana. **Veja o documento que está no Canvas.**

In [61]:
import numpy as np

# Distância euclidiana
def distancia_euclidiana(v1, v2, imagens = ""):
  de = np.linalg.norm(v1 - v2)
  print(f"Distância euclidiana entre {imagens}:", de)
  return de

In [65]:
import numpy as np

# Matrizes
imagemA = np.array([ # imagem escura
    [0.3, 0.8, 0.2],
    [0.6, 0.7, 0.4],
    [0.2, 0.5, 0.7]
    ])
imagemB = np.array([ # imagem clara
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.1, 0.2, 0.3]
    ])
imagemN = np.array([ # imagem para ser classificada
    [0.2, 0.9, 0.1],
    [0.7, 0.8, 0.3],
    [0.1, 0.4, 0.6]
])

# Converter matrizes em vetores
vA = imagemA.flatten()
vB = imagemB.flatten()
vN = imagemN.flatten()
print(vA)
print(vB)
print(vN)


# Calcular distância euclidiana
distancia_NA = distancia_euclidiana(vN, vA, "N e A")
distancia_NB = distancia_euclidiana(vN, vB, "N e B")

# Classificar similaridade (menor distância)
if distancia_NA < distancia_NB:
  classificacao = "clara"
else:
  classificacao = "escura"

print(f"Classificação: {classificacao}")

[0.3 0.8 0.2 0.6 0.7 0.4 0.2 0.5 0.7]
[0.1 0.2 0.3 0.4 0.5 0.6 0.1 0.2 0.3]
[0.2 0.9 0.1 0.7 0.8 0.3 0.1 0.4 0.6]
Distância euclidiana entre N e A: 0.3
Distância euclidiana entre N e B: 0.9695359714832658
Classificação: clara


***

### **Atividade 2**

Esta atividade consiste em criar cinco imagens com diferentes níveis de claridade, desde totalmente branca até totalmente preta, convertê-las para tons de cinza e salvá-las. Em seguida, o aluno irá carregar cada imagem no Python, por meio de bibliotecas como Pillow ou OpenCV, e redimensionar para, por exemplo, uma matriz 3×3. Logo após, esses valores de pixels serão “desenrolados” em vetores, servindo como as cinco referências de claridade. Então, o aluno produzirá ou selecionará uma nova imagem para ser processada do mesmo modo, obtendo assim um vetor que será comparado a cada uma das referências, calculando as distâncias euclidianas para determinar a qual categoria ela pertence. Ao final, a imagem nova será classificada na categoria que apresentar a menor distância. Além de ilustrar conceitos de Álgebra Linear, Geometria Analítica e manipulação de imagens, essa prática também exemplifica princípios básicos de Inteligência Artificial, mostrando como a comparação de dados numéricos (neste caso, os valores de pixels) pode levar a uma forma simples de tomada de decisão ou classificação, semelhante ao que ocorre em algoritmos de IA mais avançados.

In [ ]:
#Coloque aqui seu código